project:
  type: website
  output-dir: docs

website:
  title: "Learning Security - Cyber Security"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: basic-flow.qmd
        text: Basic Flow

  sidebar:
    - title: "Basic Flow"
      style: "docked"
      background: light
      contents:
        - section: Phase I - Research
        - basic-flow/step-1.qmd
        - basic-flow/step-2.qmd
        - basic-flow/step-3.qmd
        - basic-flow/step-4.qmd
        - basic-flow/step-5.qmd
        - basic-flow/step-6.qmd
        - section: Phase II - Learning
        - basic-flow/step-7.qmd
        - basic-flow/step-8.qmd
        - basic-flow/step-9.qmd
        - basic-flow/step-10.qmd   

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
