project:
  type: website
  output-dir: docs

website:
  title: "Learning Security - Cyber Security"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: basic-flow.qmd
        text: Basic Flow

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
