project:
  type: website
  output-dir: docs

website:
  title: "Learning Security - Cyber Security"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: user-journeys.qmd
        text: User Journeys

  sidebar:
    - title: "Home"
      style: "docked"
      background: light
      contents:
        - text: "---"
        - section: User Journeys
        - text: "---"
        - basic-flow.qmd
    - title: "Basic Flow"
      style: "docked"
      background: light
      contents:
        - text: "---"
        - section: PHASE I - Research
        - text: "---"
        - basic-flow/step-1.qmd
        - basic-flow/step-2.qmd
        - basic-flow/step-3.qmd
        - basic-flow/step-4.qmd
        - basic-flow/step-5.qmd
        - basic-flow/step-6.qmd
        - text: "---"
        - section: PHASE II - Learning
        - text: "---"
        - basic-flow/step-7.qmd
        - basic-flow/step-8.qmd
        - basic-flow/step-9.qmd
        - basic-flow/step-10.qmd   

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
